name: PR Deploy

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [dev]

  # pull_request:
  #   types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: deploy
        name: Deploy Pull Request
        uses: hngprojects/pr-deploy@main
        with:
          server_host: ${{ secrets.SERVER_HOST }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          server_password: ${{ secrets.SERVER_PASSWORD }}
          server_port: ${{ secrets.SERVER_PORT }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8000'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Preview URL
        run: |
          echo "Preview URL: ${{ steps.deploy.outputs.preview-url }}"
